// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserselfMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user_switchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _switchuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putuserpassrestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putuserpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putuserprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}
