// Code generated by hertz generator.

package audit

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getloginhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getauditloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getauditlogMw() []app.HandlerFunc {
	// your code...
	return nil
}
