// Code generated by hertz generator.

package env

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _envMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getenvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putenvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteenvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postenvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getenvallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _env0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getenvbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}
