// Code generated by Kitex v0.7.0. DO NOT EDIT.

package taskservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	task "jobor/kitex_gen/task"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetTaskAll(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskAllResp, err error)
	GetTaskById(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error)
	GetTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error)
	RunTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error)
	PostTask(ctx context.Context, Req *task.PostTaskReq, callOptions ...callopt.Option) (r *task.TaskResp, err error)
	PutTask(ctx context.Context, Req *task.PutTaskReq, callOptions ...callopt.Option) (r *task.TaskResp, err error)
	DeleteTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTaskServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTaskServiceClient struct {
	*kClient
}

func (p *kTaskServiceClient) GetTaskAll(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskAllResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTaskAll(ctx, Req)
}

func (p *kTaskServiceClient) GetTaskById(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTaskById(ctx, Req)
}

func (p *kTaskServiceClient) GetTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTask(ctx, Req)
}

func (p *kTaskServiceClient) RunTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RunTask(ctx, Req)
}

func (p *kTaskServiceClient) PostTask(ctx context.Context, Req *task.PostTaskReq, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PostTask(ctx, Req)
}

func (p *kTaskServiceClient) PutTask(ctx context.Context, Req *task.PutTaskReq, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PutTask(ctx, Req)
}

func (p *kTaskServiceClient) DeleteTask(ctx context.Context, Req *task.TaskQuery, callOptions ...callopt.Option) (r *task.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTask(ctx, Req)
}
