// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _puttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _posttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _task0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _task1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}
