// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"jobor/cmd/srv_http"
	"jobor/cmd/srv_rpc"
)

//	@title			Jobor 定时任务 API
//	@version		3.0
//	@description	支持host,server,network等
//	@description	Authorization Bearer token
//	@description	header:  x-enc-data = yes

//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@schema						Bearer

//	@contact.name	jobor
//	@contact.url	https://github.com/v-mars/jobor
//
// //@host        localhost:5002
//
//	// @BasePath /
//
// //@schemes     http
func main() {
	//dal.Init()
	//start grpc server service
	go func() {
		hlog.Fatal(srv_rpc.StartSrvRpc())
	}()
	// start http server service
	srv_http.Start()
}
