// Code generated by hertz generator.

package main

import (
	"jobor/cmd/srv_http"
	_ "jobor/docs"
)

//	@title			数据库管理平台[DBS] API
//	@version		1.0
//	@description	支持Mysql、Redis、OceanBase
//	@description	Authorization Bearer token
//	@description	header:  x-enc-data = yes

//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@schema						Bearer

//	@contact.name	UAC
//	@contact.url
//
// //@host        localhost:5616
//
//	// @BasePath /
//
// //@schemes     http
func main() {
	srv_http.Start()
}
