// Code generated by hertz generator.

package role

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getroletreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getroleallMw() []app.HandlerFunc {
	// your code...
	return nil
}
