// Code generated by Kitex v0.7.0. DO NOT EDIT.

package heartbeat

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	pbapi "jobor/kitex_gen/pbapi"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegistryWorker(ctx context.Context, Req *pbapi.RegistryReq, callOptions ...callopt.Option) (r *pbapi.Empty, err error)
	SendHeartbeat(ctx context.Context, Req *pbapi.HeartbeatReq, callOptions ...callopt.Option) (r *pbapi.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kHeartbeatClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHeartbeatClient struct {
	*kClient
}

func (p *kHeartbeatClient) RegistryWorker(ctx context.Context, Req *pbapi.RegistryReq, callOptions ...callopt.Option) (r *pbapi.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegistryWorker(ctx, Req)
}

func (p *kHeartbeatClient) SendHeartbeat(ctx context.Context, Req *pbapi.HeartbeatReq, callOptions ...callopt.Option) (r *pbapi.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendHeartbeat(ctx, Req)
}
