// Code generated by hertz generator.

package dashboard

import (
	"context"
	"jobor/biz/dal/db"
	"jobor/biz/model"
	"jobor/biz/response"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetDashboard .
//
//	@Summary		dashboard summary
//	@Description	dashboard
//	@Tags			dashboard
//
// @router /api/v1/jobor/dashboard [GET]
func GetDashboard(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.DashParam
	err = c.BindAndValidate(&req)
	if err != nil {
		response.ParamFailed(ctx, c, err)
		//response.SendBaseResp(ctx, c, err)
		return
	}

	resp := model.Dash{}
	resp, err = model.GetDash(ctx, db.DB, req)
	if err != nil {
		response.SendBaseResp(ctx, c, err)
		return
	}
	response.SendDataResp(ctx, c, response.Succeed, resp)
}
