// Code generated by hertz generator.

package sys_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _triggerupdateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapiallMw() []app.HandlerFunc {
	// your code...
	return nil
}
