// Code generated by hertz generator.

package srv_http

import (
	"context"
	"jobor/biz/handler"
	"jobor/biz/mw"
	"jobor/biz/pack/oidc_callback"
	"jobor/biz/response"
	"jobor/conf"
	_ "jobor/docs"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/panic", handler.Panic)
	r.GET(oidc_callback.GotoRedirect, oidc_callback.RedirectLogin)
	r.GET(oidc_callback.CallbackPath, oidc_callback.SsoCallback)
	r.GET("/routes", func(ctx context.Context, c *app.RequestContext) {
		routeInfo := r.Routes()
		hlog.Info(routeInfo)
		type res struct {
			Method  string `json:"method"`
			Path    string `json:"path"`
			Handler string `json:"handler"`
		}
		var data []res
		for _, v := range routeInfo {
			data = append(data, res{Method: v.Method, Path: v.Path, Handler: v.Handler})
		}
		response.SendDataResp(ctx, c, response.Succeed, data)
	})
	if conf.GetConf().Server.EnableSwagger {
		r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, swagger.DocExpansion("none")))
	}

	r.POST("/api/v1/login", mw.AuthWm.LoginHandler)
	r.GET("/api/v1/login", mw.AuthWm.LoginHandler)
	r.POST("/api/v1/logout", mw.AuthWm.LogoutHandler)
	r.GET("/api/v1/logout", mw.AuthWm.LogoutHandler)
	//r.GET("/api/v1/sys/migrate", tool.GetMigrate)
	//r.GET("/api/v1/sys/state-code", tool.GetStateCode)
	//r.POST("/api/v1/sys/gen-token", tool.GenJwtToken)
	r.POST("/api/v1/refresh_token", mw.AuthWm.RefreshHandler)
	r.GET("/api/v1/refresh_token", mw.AuthWm.RefreshHandler)
	r.StaticFS("/", &app.FS{Root: "./", GenerateIndexPages: true})
	auth := r.Group("/auth")
	auth.Use(mw.AuthWm.MiddlewareFunc())
	{
		auth.GET("/ping", handler.Ping)
	}

	// 服务api更新
	if conf.GetConf().Server.AutoUpdateApi {
		//api.UpdateApiByRoutes(db.DB, r)
	}
}
