// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

// Panic .
func Panic(ctx context.Context, c *app.RequestContext) {
	panic("Panic Test")
}
