// Code generated by hertz generator.

package worker

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putworkerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteworkerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postworkerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkerallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _worker0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkerbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkerroutingkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}
