// Code generated by Kitex v0.7.0. DO NOT EDIT.

package taskservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	pbapi "jobor/kitex_gen/pbapi"
	task "jobor/kitex_gen/task"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RunTask(ctx context.Context, Req *task.TaskRequest, callOptions ...callopt.Option) (stream TaskService_RunTaskClient, err error)
}

type TaskService_RunTaskClient interface {
	streaming.Stream
	Recv() (*pbapi.StreamResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTaskServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTaskServiceClient struct {
	*kClient
}

func (p *kTaskServiceClient) RunTask(ctx context.Context, Req *task.TaskRequest, callOptions ...callopt.Option) (stream TaskService_RunTaskClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RunTask(ctx, Req)
}
